language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-dist --dev --no-interaction
  - composer require --prefer-dist --no-interaction satooshi/php-coveralls:dev-master

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c travis.phpunit.xml

after_script:
 - php vendor/bin/coveralls -v --exclude-no-stmt

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
